#!/usr/bin/env bash
set -euo pipefail

get_script_directory() {
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd
}

directory=$(get_script_directory)
fqbn="keyboardio:avr:keyboardio_atreus"
build_directory="$directory/build/${fqbn//:/.}"

compile() {
    arduino-cli compile --fqbn "$fqbn" --output-dir "$build_directory" "$@"
}

path_personal_macros="$directory/personal_macros.h"
if [ -f "$path_personal_macros" ]; then
    compile "$@" "$directory"
else
    template="$directory/template_personal_macros.h"
    cp "$template" "$path_personal_macros"
    echo "Created personal_macros.h"
    echo "Please finalize your personal macros."
    exit 1
fi
