#!/bin/bash
echo "Hold down the Prog key on your keyboard now and keep it down."
sleep 2
arduino-cli upload \
    --port /dev/ttyACM0 \
    --fqbn keyboardio:avr:keyboardio_atreus \
    --verbose "$@"
echo "Done. You can let go of the Prog key now."
